CREATE WAREHOUSE ENERGY_WH;
CREATE DATABASE ENERGY_HUB;
CREATE SCHEMA INGESTION;
CREATE SCHEMA PIPES;
CREATE SCHEMA STAGING;
CREATE SCHEMA BUSINESS;
CREATE TABLE ENERGY_HUB.INGESTION.RAW_DATA (
    READING_ID NUMBER
    ,METER_ID VARCHAR(6)
    ,TIMESTAMP DATETIME
    ,LOCATION VARCHAR(20)
    ,ENERGY_CONSUMPTION_KWH DECIMAL
    ,SOLAR_GENERATION_KWH DECIMAL
    ,VOLTAGE NUMBER
    ,CURRENT_TEMPERATURE_C DECIMAL
);
