USE DATABASE ENERGY_HUB;
USE SCHEMA BUSINESS;

-- Create a view highlighting the amount of different invalid validations per date.
CREATE OR REPLACE VIEW INVALID_STATUS_PER_DATE AS
SELECT
    TIMESTAMP::TIMESTAMP::DATE AS DATE_VALUE,
    QUALITY_STATUS,
    COUNT(*) AS QUANTITY
FROM ENERGY_HUB.STAGING.METER_READINGS
WHERE QUALITY_STATUS != 'VALID'
GROUP BY DATE_VALUE, QUALITY_STATUS
ORDER BY DATE_VALUE ASC;

-- Select all to validate view was correctly created.
SELECT * FROM ENERGY_HUB.BUSINESS.INVALID_STATUS_PER_DATE;
