USE DATABASE ENERGY_HUB;
USE SCHEMA BUSINESS;

-- Create a view highlighting the amount of different invalid validations per date.
CREATE OR REPLACE VIEW INVALID_STATUS_PER_DATE AS
SELECT
    TIMESTAMP::DATE AS DATE_VALUE,
    QUALITY_STATUS,
    COUNT(*) AS QUANTITY
FROM ENERGY_HUB.STAGING.METER_READINGS
WHERE QUALITY_STATUS != 'VALID'
GROUP BY DATE_VALUE, QUALITY_STATUS
ORDER BY DATE_VALUE ASC;

-- Select all to validate view was correctly created.
SELECT * FROM ENERGY_HUB.BUSINESS.INVALID_STATUS_PER_DATE;

-- Create a view summarizing the ovarall quality statusses, using the count of distinct statusses
CREATE OR REPLACE VIEW QUALITY_STATUS_SUMMARY AS
SELECT
    QUALITY_STATUS,
    COUNT(*) AS QUANTITY
FROM ENERGY_HUB.STAGING.METER_READINGS
GROUP BY QUALITY_STATUS;

SELECT * FROM ENERGY_HUB.BUSINESS.QUALITY_STATUS_SUMMARY;

-- Create a view summarizing the overall usage for the past 30 days.
CREATE OR REPLACE VIEW USAGE_SUMMARY_PAST_MONTH AS
SELECT
    COUNT(*) AS TOTAL_VALID_READINGS,
    AVG(ENERGY_CONSUMPTION_KWH) AS AVERAGE_CONSUMPTION_KWH,
    AVG(SOLAR_GENERATION_KWH) AS AVERAGE_SOLAR_GENERATION_KWH,
    SUM(ENERGY_CONSUMPTION_KWH) AS TOTAL_CONSUMPTION_KWH,
    SUM(SOLAR_GENERATION_KWH) AS TOTAL_SOLAR_GENERATION_KWH,
    SUM(ENERGY_CONSUMPTION_KWH - SOLAR_GENERATION_KWH) AS NET_CONSUMPTION_KWH
FROM ENERGY_HUB.STAGING.METER_READINGS
WHERE TIMESTAMP >= DATEADD(DAY, -30, CURRENT_TIMESTAMP())
    AND QUALITY_STATUS = 'VALID';

-- Select all to validate view was correctly created.
SELECT * FROM ENERGY_HUB.BUSINESS.USAGE_SUMMARY_PAST_MONTH;

-- Create a view summarizing daily usage per location.
CREATE OR REPLACE VIEW DAILY_USAGE_PER_LOCATION AS
SELECT
    TIMESTAMP::DATE AS DATE_VALUE,
    LOCATION,
    COUNT(*) AS TOTAL_READINGS,
    AVG(ENERGY_CONSUMPTION_KWH) AS AVERAGE_CONSUMPTION_KWH,
    AVG(SOLAR_GENERATION_KWH) AS AVERAGE_SOLAR_GENERATION_KWH,
    SUM(ENERGY_CONSUMPTION_KWH) AS TOTAL_CONSUMPTION_KWH,
    SUM(SOLAR_GENERATION_KWH) AS TOTAL_SOLAR_GENERATION_KWH,
    SUM(ENERGY_CONSUMPTION_KWH - SOLAR_GENERATION_KWH) AS NET_CONSUMPTION_KWH
FROM ENERGY_HUB.STAGING.METER_READINGS
WHERE QUALITY_STATUS = 'VALID'
GROUP BY DATE_VALUE, LOCATION
ORDER BY DATE_VALUE ASC, LOCATION ASC;

-- Select all to validate view was correctly created.
SELECT * FROM ENERGY_HUB.BUSINESS.DAILY_USAGE_PER_LOCATION;
