USE DATABASE ENERGY_HUB;
CREATE SCHEMA BUSINESS;

SELECT * FROM ENERGY_HUB.STAGING.METER_READINGS;

CREATE OR REPLACE VIEW INVALID_STATUS_PER_DATE AS
SELECT
    TIMESTAMP::TIMESTAMP::DATE AS DATE_VALUE,
    QUALITY_STATUS,
    COUNT(*) AS QUANTITY
FROM ENERGY_HUB.STAGING.METER_READINGS
WHERE QUALITY_STATUS != 'VALID'
GROUP BY DATE_VALUE, QUALITY_STATUS
ORDER BY DATE_VALUE ASC;

SELECT * FROM ENERGY_HUB.BUSINESS.INVALID_STATUS_PER_DATE;
SELECT * FROM STAGING.METER_READINGS;
