CREATE WAREHOUSE ENEXIS_WH;
CREATE DATABASE ENERGY_HUB;
CREATE SCHEMA TABLES;
CREATE SCHEMA PIPES;
CREATE TABLE RAW_METER_DATA (
    READING_ID NUMBER
    ,METER_ID VARCHAR(6)
    ,TIMESTAMP DATETIME
    ,LOCATION VARCHAR(20)
    ,ENERGY_CONSUMPTION_KWH DECIMAL
    ,SOLAR_GENERATION_KWH DECIMAL
    ,VOLTAGE NUMBER
    ,CURRENT_TEMPERATURE_C DECIMAL
);
