USE DATABASE ENERGY_HUB;
USE SCHEMA VIEWS;

-- Create a staging view and cleanup data
-- Cleanups:
-- Trim and set first character of location to uppercase
-- Validate on null values, high or low consumption / generation or temperatures
CREATE OR REPLACE VIEW STAGING_VIEW (READING_ID, METER_ID, TIMESTAMP, LOCATION, ENERGY_CONSUMPTION_KWH, SOLAR_GENERATION_KWH, VOLTAGE, CURRENT_TEMPERATURE_C, VALIDATION) AS
SELECT 
    READING_ID,
    METER_ID,
    TIMESTAMP,
    INITCAP(TRIM(LOCATION)),
    ENERGY_CONSUMPTION_KWH,
    SOLAR_GENERATION_KWH,
    VOLTAGE,
    CURRENT_TEMPERATURE_C,
    CASE
        WHEN METER_ID IS NULL THEN 'MISSING_METER_ID'
        WHEN TIMESTAMP IS NULL THEN 'MISSING_TIMESTAMP'
        WHEN ENERGY_CONSUMPTION_KWH < 0 THEN 'NEGATIVE_CONSUMPTION'
        WHEN ENERGY_CONSUMPTION_KWH > 20 THEN 'HIGH_CONSUMPTION'
        WHEN SOLAR_GENERATION_KWH < 0 THEN 'NEGATIVE_GENERATION'
        WHEN SOLAR_GENERATION_KWH > 20 THEN 'HIGH_GENERATION'
        WHEN VOLTAGE IS NULL THEN 'MISSING_VOLTAGE'
        WHEN VOLTAGE < 200 THEN 'LOW_VOLTAGE'
        WHEN VOLTAGE > 250 THEN 'HIGH_VOLTAGE'
        WHEN CURRENT_TEMPERATURE_C > 40 THEN 'HIGH_TEMPERATURE'
        ELSE 'VALID'
    END AS QUALITY_STATUS
FROM ENERGY_HUB.TABLES.RAW_METER_DATA;
